config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root  'sightseens#index'
  
  resources :tops, only: [:index, :show]
  
  resources :sightseens, only: [:index, :show] do
    collection do
      get 'search'
    end
  end

  resources :restaurants, only: [:index, :show]  do
    collection do
      get 'search'
    end
  end

  resources :spas, only: [:index, :show] do
    collection do
      get 'search'
    end
  end

  resources :souvenirs do
    collection do
      get 'search'
    end
  end

  resources :specialities do
    collection do
      get 'search'
    end
  end

  resources :localbrands do
    collection do
      get 'search'
    end
  end

  resources :shoppings, only: [:index, :show] do
    collection do
      get 'search'
    end
  end

  resources :nightspots do
    collection do
      get 'search'
    end
  end

  resources :accommodations, only: [:index, :show] do
    collection do
      get 'search'
    end
  end

  resources :schools do
    collection do
      get 'search'
    end
  end

  resources :islands, only: [:index, :show] do
    collection do
      get 'search'
    end
  end

  resources :tours, only: [:index, :show] do
    collection do
      get 'search'
    end
  end

  resources :transportations do
    collection do
      get 'search'
    end
  end

  resources :generals, :only => :index
  resources :weathers, :only => :index
  
end

app/models/accommodation.rb
class Accommodation < ApplicationRecord
end

app/models/general.rb
class General < ApplicationRecord
end

app/models/island.rb
class Island < ApplicationRecord
end

app/models/localbrand.rb
class Localbrand < ApplicationRecord
end

app/models/nightspot.rb
class Nightspot < ApplicationRecord
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord



  
end

app/models/school.rb
class School < ApplicationRecord
end

app/models/shopping.rb
class Shopping < ApplicationRecord
end

app/models/sightseen.rb
class Sightseen < ApplicationRecord
end

app/models/souvenir.rb
class Souvenir < ApplicationRecord
end

app/models/spa.rb
class Spa < ApplicationRecord
end

app/models/speciality.rb
class Speciality < ApplicationRecord
end

app/models/tour.rb
class Tour < ApplicationRecord
end

app/models/transportation.rb
class Transportation < ApplicationRecord
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController

  def index
    @targets = Island.all.order(name_ja: "ASC")
    @num_targets = @targets.count
    @list_categorys = Island.select(:category_ja).distinct.order(category_ja: "ASC")
    @list_areas = Island.select(:departure_area_ja).distinct.order(departure_area_ja: "ASC")
    @q = Island.ransack(params[:q])
    @search_results = @q.result(distinct: true)
    gon.target_datas = @targets
  end
  
  def search
    @list_categorys = Island.select(:category_ja).distinct.order(category_ja: "ASC")
    @list_areas = Island.select(:departure_area_ja).distinct.order(departure_area_ja: "ASC")
    @q = Island.search(search_params)
    @search_results = @q.result(distinct: true).order(name_ja: "ASC")
    @num_targets = @search_results.count
  end

  def show
    @target = Island.find(params[:id])
    gon.target_datas = @target
  end

  private
  def search_params
    params.require(:q).permit!
  end

end

app/helpers/generals_helper.rb
module GeneralsHelper
end

app/helpers/islands_helper.rb
module IslandsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/shoppings_helper.rb
module ShoppingsHelper
end

app/helpers/spas_helper.rb
module SpasHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/islands/index.html.erb
<div class="container">
  <div class="search_area">

    <div class="search-drawer">
      <input id="search-input" type="checkbox" class="search-unshown">
      <label id="search-open" for="search-input">絞り込み検索</label>
      <label class="search-unshown" id="search-close" for="search-input"></label>
      <div class="search-content">
        <div class="search_title">絞り込み検索</div>
        <%= search_form_for(@q, url: search_islands_path) do |f| %>
          <fieldset>
            <legend>対象</legend>
            <ul>
              <% @list_categorys.each do |list| %>
                <li>
                  <%= f.check_box :category_ja_eq_any, { multiple: true }, list.category_ja, nil %><%= list.category_ja %>
                </li>
              <% end %>
            </ul>
          </fieldset>
          <fieldset>
            <legend>出発エリア</legend>
            <ul>
              <% @list_areas.each do |list| %>
                <li>
                  <%= f.check_box :departure_area_ja_eq_any, { multiple: true }, list.departure_area_ja, nil %><%= list.departure_area_ja %>
                </li>
              <% end %>
            </ul>
          </fieldset>
          <fieldset>
            <legend>キーワード</legend>
            <%= f.search_field :name_ja_or_name_en_or_category_ja_or_category_en_or_departure_area_ja_or_departure_area_en_or_description_ja_cont ,class: "text_search"%>
            </fieldset>

          <div class="btn_wrapper">
            <%= f.submit "この条件で探す", class: "btn" %>
          </div>
        <% end %>
      </div>  
    </div>
  </div> 
  <main>
    <div class="number">全<%= @num_targets %>件</div>
    <div class="content">
      <% @targets.each do |target| %>
        <div class="content_wrap">
          <div class="name_area">
            <div class="name">  
              <% if target.flag_show === "yes" %>
                  <h2><%= link_to "#{target.name_ja}", "/islands/#{target.id}", method: :get %></h2>
                  <p><%= link_to "#{target.name_en}", "/islands/#{target.id}", method: :get %></p>
                <% else %>
                  <h2><%= target.name_ja %></h2>
                  <p><%= target.name_en %></p>
              <% end %>
            </div>
            <div class="tag_area">
              <div class="search_tag"><%= target.category_ja %></div>  
              <div class="search_tag"><%= target.departure_area_ja %></div>
            </div>
          </div>
    
          <div class="content_area">
            <div class="pic_area">
              <div class="pic_main">
              <% if target.picture1 %>
                  <img src="/assets/<%= target.picture1 %>" id="pic_main_<%= target.id %>">
                <% else %>
                  <img src="/assets/comming_soon.jpg" id="pic_main_<%= target.id %>">
              <% end %>
              </div>
              <div class="pic_sub">
                <% if target.picture1 %>
                    <img src="/assets/<%= target.picture1 %>" id="pic_sub1_<%= target.id %>">
                  <% else %>
                    <img src="/assets/comming_soon.jpg" id="pic_sub1_<%= target.id %>">
                <% end %>
                <% if target.picture2 %>
                    <img src="/assets/<%= target.picture2 %>" id="pic_sub2_<%= target.id %>" >
                  <% else %>
                    <img src="/assets/comming_soon.jpg" id="pic_sub2_<%= target.id %>">
                <% end %>
                <% if target.picture3 %>
                    <img src="/assets/<%= target.picture3 %>" id="pic_sub3_<%= target.id %>">
                  <% else %>
                    <img src="/assets/comming_soon.jpg" id="pic_sub3_<%= target.id %>">
                <% end %>
              </div>
            </div>
            <div class="article_area">
              <div class="description">
                <%= target.description_ja %>
              </div>
              <div class="non_description">
                <div class="non_description_item">
                  <span class="material-icons md-18">flag</span> <a href="<%=target.mapurl_departure %>" target="_blank"><%= target.departure_point_ja %>(<%= target.departure_point_en %>)</a>
                </div>
                <div class="non_description_item">
                  <span class="material-icons md-18">directions_boat</span> <%= target.transportation_ja %> <%= target.transportation_time_ja %>
                </div>
                <div class="non_description_item">
                  <span class="material-icons md-18">payment</span> <%= target.price_ja %>
                </div>
                <div class="non_description_item">
                  <% if target.mapurl.blank? or target.mapurl === "-"  %>
                    <span class="material-icons md-18">place</span> <%= target.address %>
                  <% else %>
                    <span class="material-icons md-18">place</span> <a href="<%=target.mapurl %>" target="_blank"><%= target.address %></a>
                  <% end %>
                </div>
                <% if target.url.present? and target.url != "-"  %>
                  <div class="non_description_item">
                    <span class="material-icons md-18">home</span> <a href="<%= target.url %>" target="_blank"><%= target.url %></a>
                  </div>                  
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </main>
  
  <aside>
  </aside>
</div>

app/views/islands/search.html.erb
<div class="container">
  <div class="search_area">

    <div class="search-drawer">
      <input id="search-input" type="checkbox" class="search-unshown">
      <label id="search-open" for="search-input">絞り込み検索</label>
      <label class="search-unshown" id="search-close" for="search-input"></label>
  
      <div class="search-content">
        <div class="search_title">絞り込み検索</div>
        <%= search_form_for(@q, url: search_islands_path) do |f| %>
          <fieldset>
            <legend>対象</legend>
            <ul>
              <% @list_categorys.each do |list| %>
                <li>
                  <%= f.check_box :category_ja_eq_any, { multiple: true }, list.category_ja, nil %><%= list.category_ja %>
                </li>
              <% end %>
            </ul>
          </fieldset>
          <fieldset>
            <legend>出発エリア</legend>
            <ul>
              <% @list_areas.each do |list| %>
                <li>
                  <%= f.check_box :departure_area_ja_eq_any, { multiple: true }, list.departure_area_ja, nil %><%= list.departure_area_ja %>
                </li>
              <% end %>
            </ul>
          </fieldset>
          <fieldset>
            <legend>キーワード</legend>
            <%= f.search_field :name_ja_or_name_en_or_category_ja_or_category_en_or_departure_area_ja_or_departure_area_en_or_description_ja_cont ,class: "text_search"%>
            </fieldset>

          <div class="btn_wrapper">
            <%= f.submit "この条件で探す", class: "btn" %>
          </div>
        <% end %>
      
      </div>
    </div>
  </div>

  <main>
    <div class="number">全<%= @num_targets %>件</div>
    <% if @num_targets >0 %>
      <div class="content">
        <% @search_results.each do |target| %>
          <div class="content_wrap">
            <div class="name_area">
              <div class="name">  
                <% if target.flag_show === "yes" %>
                    <h2><%= link_to "#{target.name_ja}", "/islands/#{target.id}", method: :get %></h2>
                    <p><%= link_to "#{target.name_en}", "/islands/#{target.id}", method: :get %></p>
                  <% else %>
                    <h2><%= target.name_ja %></h2>
                    <p><%= target.name_en %></p>
                <% end %>
              </div>
              <div class="tag_area">
                <div class="search_tag"><%= target.category_ja %></div>  
                <div class="search_tag"><%= target.departure_area_ja %></div>
              </div>
            </div>
      
            <div class="content_area">
              <div class="pic_area">
                <div class="pic_main">
                <% if target.picture1 %>
                    <img src="/assets/<%= target.picture1 %>" id="pic_main_<%= target.id %>">
                  <% else %>
                    <img src="/assets/comming_soon.jpg" id="pic_main_<%= target.id %>">
                <% end %>
                </div>
                <div class="pic_sub">
                  <% if target.picture1 %>
                      <img src="/assets/<%= target.picture1 %>" id="pic_sub1_<%= target.id %>">
                    <% else %>
                      <img src="/assets/comming_soon.jpg" id="pic_sub1_<%= target.id %>">
                  <% end %>
                  <% if target.picture2 %>
                      <img src="/assets/<%= target.picture2 %>" id="pic_sub2_<%= target.id %>" >
                    <% else %>
                      <img src="/assets/comming_soon.jpg" id="pic_sub2_<%= target.id %>">
                  <% end %>
                  <% if target.picture3 %>
                      <img src="/assets/<%= target.picture3 %>" id="pic_sub3_<%= target.id %>">
                    <% else %>
                      <img src="/assets/comming_soon.jpg" id="pic_sub3_<%= target.id %>">
                  <% end %>
                </div>
              </div>
              <div class="article_area">
                <div class="description">
                  <%= target.description_ja %>
                </div>
                <div class="non_description">
                  <div class="non_description_item">
                    <span class="material-icons md-18">flag</span> <a href="<%=target.mapurl_departure %>" target="_blank"><%= target.departure_point_ja %>(<%= target.departure_point_en %>)</a>
                  </div>
                  <div class="non_description_item">
                    <span class="material-icons md-18">directions_boat</span> <%= target.transportation_ja %> <%= target.transportation_time_ja %>
                  </div>
                  <div class="non_description_item">
                    <span class="material-icons md-18">payment</span> <%= target.price_ja %>
                  </div>
                  <div class="non_description_item">
                    <% if target.mapurl.blank? or target.mapurl === "-"  %>
                      <span class="material-icons md-18">place</span> <%= target.address %>
                    <% else %>
                      <span class="material-icons md-18">place</span> <a href="<%=target.mapurl %>" target="_blank"><%= target.address %></a>
                    <% end %>
                  </div>
                  <% if target.url.present? and target.url != "-"  %>
                    <div class="non_description_item">
                      <span class="material-icons md-18">home</span> <a href="<%= target.url %>" target="_blank">Webサイトを見る</a>
                    </div>                        
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <p>指定の条件に合致するものがみつかりませんでした。</p>
      <p>絞り込み条件を変更して探してみてください。</p>
    <% end %>
  </main>
  
  <aside>
  </aside>
</div>

app/views/islands/show.html.erb
<div class="show_container">
  <main>
    <%= link_to("前ページに戻る", :back, class:"show_btn") %>

    <div class="name_area">
      <div class="name">
        <h2><%= @target.name_ja %></h2>
        <p><%= @target.name_en %></p>
      </div>
      <div class="tag_area">
        <div class="search_tag"><%= @target.category_ja %></div>  
        <div class="search_tag"><%= @target.departure_area_ja %></div>
      </div>
    </div>

    <div class="show_pic_area">
      <div class="show_pic_main_area">
        <% if @target.picture1 %>
            <img src="/assets/<%= @target.picture1 %>" id="pic_main_<%= @target.id %>">
          <% else %>
            <img src="/assets/comming_soon.jpg" id="pic_main_<%= @target.id %>">
        <% end %> 
      </div>
      <div class="show_pic_sub_area">
        <% if @target.picture1 %>
            <img src="/assets/<%= @target.picture1 %>" id="pic_sub1_<%= @target.id %>">
          <% else %>
            <img src="/assets/comming_soon.jpg" id="pic_sub1_<%= @target.id %>">
        <% end %>
        <% if @target.picture2 %>
            <img src="/assets/<%= @target.picture2 %>" id="pic_sub2_<%= @target.id %>" >
          <% else %>
            <img src="/assets/comming_soon.jpg" id="pic_sub2_<%= @target.id %>">
        <% end %>
        <% if @target.picture3 %>
          <img src="/assets/<%= @target.picture3 %>" id="pic_sub3_<%= @target.id %>">
          <% else %>
          <img src="/assets/comming_soon.jpg" id="pic_sub3_<%= @target.id %>">
        <% end %>
        <% if @target.picture4 %>
          <img src="/assets/<%= @target.picture4 %>" id="pic_sub4_<%= @target.id %>">
        <% end %>
        <% if @target.picture5 %>
          <img src="/assets/<%= @target.picture5 %>" id="pic_sub5_<%= @target.id %>">
        <% end %>
        <% if @target.picture6 %>
          <img src="/assets/<%= @target.picture6 %>" id="pic_sub6_<%= @target.id %>">
        <% end %>
        <% if @target.picture7 %>
          <img src="/assets/<%= @target.picture7 %>" id="pic_sub7_<%= @target.id %>">
        <% end %>
        <% if @target.picture8 %>
          <img src="/assets/<%= @target.picture8 %>" id="pic_sub8_<%= @target.id %>">
        <% end %>
      </div>
    </div>

    <div class="show_description">
      <h3>概要</h3>
      <div class="show_article_area">
        <div class="show_article"><%= @target.description_ja %></div>
      </div>

      <% if @target.highlight1.present? %>
        <h3>見所</h3>
        <div class="show_article_area">
            <h4>見所1</h4>
            <div class="show_highlight_article_area">
              <div class="show_article_highlight"><%= @target.highlight1 %></div>
              <div class="show_pic_artcile_area_highlight"><img src="/assets/<%= @target.highlight1_pic %>"></div>
            </div>
          <% if @target.highlight2.present? %>
            <h4>見所2</h4>
            <div class="show_highlight_article_area">
              <div class="show_article_highlight"><%= @target.highlight2 %></div>
              <div class="show_pic_artcile_area_highlight"><img src="/assets/<%= @target.highlight2_pic %>"></div>
            </div>
          <% end %>
          <% if @target.highlight3.present? %>
            <h4>見所3</h4>
            <div class="show_highlight_article_area">
              <div class="show_article_highlight"><%= @target.highlight3 %></div>
              <div class="show_pic_artcile_area_highlight"><img src="/assets/<%= @target.highlight3_pic %>"></div>
            </div>
          <% end %>
        </div>
      <% end %>

      <% if @target.guide_map.present? %>
        <h3>案内図</h3>
        <div class="show_article_area">
          <div class="show_article"><%= @target.guide %></div>
          <div class="show_pic_artcile_area_guide"><img src="/assets/<%= @target.guide_map %>"></div>
        </div>
      <% end %>

      <% if @target.direction1.present? %>
        <h3>行き方</h3>
        <div class="show_article_area">
            <div class="show_article"><%= @target.direction1 %></div>
          <% if @target.direction2.present? %>
            <div class="show_article"><%= @target.direction2 %></div>
          <% end %>
          <% if @target.direction3.present? %>
           <div class="show_article"><%= @target.direction3 %></div>
          <% end %>
        </div>
      <% end %>

      <h3>関連ツアー</h3>
      <div class="show_article_area">
        <div class="show_article">xx</div>
      </div>
    </div>

    <div class="show_bottom_btns">
      <a href="#" class="show_btn">先頭に戻る</a>
      <%= link_to("前ページに戻る", :back, class:"show_btn") %>
    </div>
  </main>
</div>