config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root  'sightseens#index'
  
  resources :tops, only: [:index, :show]
  
  resources :sightseens, only: [:index, :show] do
    collection do
      get 'search'
    end
  end

  resources :restaurants, only: [:index, :show]  do
    collection do
      get 'search'
    end
  end

  resources :spas, only: [:index, :show] do
    collection do
      get 'search'
    end
  end

  resources :souvenirs do
    collection do
      get 'search'
    end
  end

  resources :specialities do
    collection do
      get 'search'
    end
  end

  resources :localbrands do
    collection do
      get 'search'
    end
  end

  resources :shoppings, only: [:index, :show] do
    collection do
      get 'search'
    end
  end

  resources :nightspots do
    collection do
      get 'search'
    end
  end

  resources :accommodations, only: [:index, :show] do
    collection do
      get 'search'
    end
  end

  resources :schools do
    collection do
      get 'search'
    end
  end

  resources :islands, only: [:index, :show] do
    collection do
      get 'search'
    end
  end

  resources :tours, only: [:index, :show] do
    collection do
      get 'search'
    end
  end

  resources :transportations do
    collection do
      get 'search'
    end
  end

  resources :generals, :only => :index
  resources :weathers, :only => :index
  
end

app/models/accommodation.rb
class Accommodation < ApplicationRecord
end

app/models/general.rb
class General < ApplicationRecord
end

app/models/island.rb
class Island < ApplicationRecord
end

app/models/localbrand.rb
class Localbrand < ApplicationRecord
end

app/models/nightspot.rb
class Nightspot < ApplicationRecord
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord



  
end

app/models/school.rb
class School < ApplicationRecord
end

app/models/shopping.rb
class Shopping < ApplicationRecord
end

app/models/sightseen.rb
class Sightseen < ApplicationRecord
end

app/models/souvenir.rb
class Souvenir < ApplicationRecord
end

app/models/spa.rb
class Spa < ApplicationRecord
end

app/models/speciality.rb
class Speciality < ApplicationRecord
end

app/models/tour.rb
class Tour < ApplicationRecord
end

app/models/transportation.rb
class Transportation < ApplicationRecord
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

  def index
    @targets = School.all.order(name_ja: "ASC")
    @num_targets = @targets.count
    @list_categorys = School.select(:category_ja).distinct.order(category_ja: "ASC")
    @list_areas = School.select(:area_ja).distinct.order(area_ja: "ASC")
    @q = School.ransack(params[:q])
    @search_results = @q.result(distinct: true)
    gon.target_datas = @targets
  end
  
  def search
    @list_categorys = School.select(:category_ja).distinct.order(category_ja: "ASC")
    @list_areas = School.select(:area_ja).distinct.order(area_ja: "ASC")
    @q = School.search(search_params)
    @search_results = @q.result(distinct: true).order(name_ja: "ASC")
    @num_targets = @search_results.count
  end

  private
  def search_params
    params.require(:q).permit!
  end


end

app/helpers/generals_helper.rb
module GeneralsHelper
end

app/helpers/islands_helper.rb
module IslandsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/shoppings_helper.rb
module ShoppingsHelper
end

app/helpers/spas_helper.rb
module SpasHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/schools/index.html.erb
<div class="container">
  <div class="search_area">

    <div class="search-drawer">
      <input id="search-input" type="checkbox" class="search-unshown">
      <label id="search-open" for="search-input">絞り込み検索</label>
      <label class="search-unshown" id="search-close" for="search-input"></label>
      <div class="search-content">
        <div class="search_title">絞り込み検索</div>
        <%= search_form_for(@q, url: search_schools_path) do |f| %>
          <fieldset>
            <legend>対象</legend>
            <ul>
              <% @list_categorys.each do |list| %>
                <li>
                  <%= f.check_box :category_ja_eq_any, { multiple: true }, list.category_ja, nil %><%= list.category_ja %>
                </li>
              <% end %>
            </ul>
          </fieldset>
          <fieldset>
            <legend>エリア</legend>
            <ul>
              <% @list_areas.each do |list| %>
                <li>
                  <%= f.check_box :area_ja_eq_any, { multiple: true }, list.area_ja, nil %><%= list.area_ja %>
                </li>
              <% end %>
            </ul>
          </fieldset>
          <fieldset>
            <legend>キーワード</legend>
            <%= f.search_field :name_ja_or_name_en_or_category_ja_or_category_en_or_area_ja_or_area_en_or_description_ja_cont ,class: "text_search"%>
            </fieldset>

          <div class="btn_wrapper">
            <%= f.submit "この条件で探す", class: "btn" %>
          </div>
        <% end %>
      </div>  
    </div>
  </div> 
  <main>
    <div class="number">全<%= @num_targets %>件</div>
    <div class="content">
      <% @targets.each do |target| %>
        <div class="content_wrap">
          <div class="name_area">
            <div class="name">  
              <h2><%= target.name_ja %></h2>
              <p><%= target.name_en %></p>
            </div>
            <div class="tag_area">
              <div class="search_tag"><%= target.category_ja %></div>  
              <div class="search_tag"><%= target.area_ja %></div>
            </div>
          </div>
    
          <div class="content_area">
            <div class="pic_area">
              <div class="pic_main">
              <% if target.picture1 %>
                  <img src="/assets/<%= target.picture1 %>" id="pic_main_<%= target.id %>">
                <% else %>
                  <img src="/assets/comming_soon.jpg" id="pic_main_<%= target.id %>">
              <% end %>
              </div>
              <div class="pic_sub">
                <% if target.picture1 %>
                    <img src="/assets/<%= target.picture1 %>" id="pic_sub1_<%= target.id %>">
                  <% else %>
                    <img src="/assets/comming_soon.jpg" id="pic_sub1_<%= target.id %>">
                <% end %>
                <% if target.picture2 %>
                    <img src="/assets/<%= target.picture2 %>" id="pic_sub2_<%= target.id %>" >
                  <% else %>
                    <img src="/assets/comming_soon.jpg" id="pic_sub2_<%= target.id %>">
                <% end %>
                <% if target.picture3 %>
                    <img src="/assets/<%= target.picture3 %>" id="pic_sub3_<%= target.id %>">
                  <% else %>
                    <img src="/assets/comming_soon.jpg" id="pic_sub3_<%= target.id %>">
                <% end %>
              </div>
            </div>
            <div class="article_area">
              <div class="description">
                <%= target.description_ja %>
              </div>
              <div class="non_description">
                <div class="non_description_item">
                  <% if target.mapurl.blank? or target.mapurl === "-"  %>
                    <span class="material-icons md-18">place</span> <%= target.address %>
                  <% else %>
                    <span class="material-icons md-18">place</span> <a href="<%=target.mapurl %>" target="_blank"><%= target.address %></a>
                  <% end %>
                </div>
                <% if target.url.present? and target.url != "-"  %>
                  <div class="non_description_item">
                    <span class="material-icons md-18">home</span> <a href="<%= target.url %>" target="_blank"><%= target.url %></a>
                  </div>
                <% end %>                    
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </main>
  
  <aside>
  </aside>
</div>

app/views/schools/search.html.erb
<div class="container">
  <div class="search_area">

    <div class="search-drawer">
      <input id="search-input" type="checkbox" class="search-unshown">
      <label id="search-open" for="search-input">絞り込み検索</label>
      <label class="search-unshown" id="search-close" for="search-input"></label>
  
      <div class="search-content">
        <div class="search_title">絞り込み検索</div>
        <%= search_form_for(@q, url: search_schools_path) do |f| %>
          <fieldset>
            <legend>対象</legend>
            <ul>
              <% @list_categorys.each do |list| %>
                <li>
                  <%= f.check_box :category_ja_eq_any, { multiple: true }, list.category_ja, nil %><%= list.category_ja %>
                </li>
              <% end %>
            </ul>
          </fieldset>
          <fieldset>
            <legend>エリア</legend>
            <ul>
              <% @list_areas.each do |list| %>
                <li>
                  <%= f.check_box :area_ja_eq_any, { multiple: true }, list.area_ja, nil %><%= list.area_ja %>
                </li>
              <% end %>
            </ul>
          </fieldset>
          <fieldset>
            <legend>キーワード</legend>
            <%= f.search_field :name_ja_or_name_en_or_category_ja_or_category_en_or_area_ja_or_area_en_or_description_ja_cont ,class: "text_search"%>
            </fieldset>

          <div class="btn_wrapper">
            <%= f.submit "この条件で探す", class: "btn" %>
          </div>
        <% end %>
      
      </div>
    </div>
  </div>

  <main>
    <div class="number">全<%= @num_targets %>件</div>
    <% if @num_targets >0 %>
      <div class="content">
        <% @search_results.each do |target| %>
          <div class="content_wrap">
            <div class="name_area">
              <div class="name">  
                <h2><%= target.name_ja %></h2>
                <p><%= target.name_en %></p>
              </div>
              <div class="tag_area">
                <div class="search_tag"><%= target.category_ja %></div>  
                <div class="search_tag"><%= target.area_ja %></div>
              </div>
            </div>
      
            <div class="content_area">
              <div class="pic_area">
                <div class="pic_main">
                <% if target.picture1 %>
                    <img src="/assets/<%= target.picture1 %>" id="pic_main_<%= target.id %>">
                  <% else %>
                    <img src="/assets/comming_soon.jpg" id="pic_main_<%= target.id %>">
                <% end %>
                </div>
                <div class="pic_sub">
                  <% if target.picture1 %>
                      <img src="/assets/<%= target.picture1 %>" id="pic_sub1_<%= target.id %>">
                    <% else %>
                      <img src="/assets/comming_soon.jpg" id="pic_sub1_<%= target.id %>">
                  <% end %>
                  <% if target.picture2 %>
                      <img src="/assets/<%= target.picture2 %>" id="pic_sub2_<%= target.id %>" >
                    <% else %>
                      <img src="/assets/comming_soon.jpg" id="pic_sub2_<%= target.id %>">
                  <% end %>
                  <% if target.picture3 %>
                      <img src="/assets/<%= target.picture3 %>" id="pic_sub3_<%= target.id %>">
                    <% else %>
                      <img src="/assets/comming_soon.jpg" id="pic_sub3_<%= target.id %>">
                  <% end %>
                </div>
              </div>
              <div class="article_area">
                <div class="description">
                  <%= target.description_ja %>
                </div>
                <div class="non_description">
                  <div class="non_description_item">
                    <% if target.mapurl.blank? or target.mapurl === "-"  %>
                      <span class="material-icons md-18">place</span> <%= target.address %>
                    <% else %>
                      <span class="material-icons md-18">place</span> <a href="<%=target.mapurl %>" target="_blank"><%= target.address %></a>
                    <% end %>
                  </div>
                  <% if target.url.present? and target.url != "-"  %>
                    <div class="non_description_item">
                      <span class="material-icons md-18">home</span> <a href="<%= target.url %>" target="_blank">Webサイトを見る</a>
                    </div>
                  <% end %>                      
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <p>指定の条件に合致するものがみつかりませんでした。</p>
      <p>絞り込み条件を変更して探してみてください。</p>
    <% end %>
  </main>
  
  <aside>
  </aside>
</div>